### ISSUE TITLE
Data Cleaning

### ISSUE THREAD

**Issue by vu13** [vu13/DS311GroupProject#3]
- [x] Columns are Correct
- [x] Duplicate Values
- [x] Whitespaces

Identify Missing values(not sure what to do about it yet)
-There were a lot of missing values that we don't know to remove yet, certain columns seem pointless and filled with missing values

**Comment by lilcapu** [comment]
I'm working on the duplicate values in Tableau but will move to jupyter to code it. As for whitespaces I believe the function strip() will do the trick in removing white spaces.

**Comment by lilcapu** [comment]
Hey guys, I found a way to deal with those pesky duplicate values and white spaces, that is why I'm marking this task as done and finally closing it. If you guys check out my latest update, you might have an idea on how I did it, but if you want to know, just let me know!!
